// Generated by Copilot
import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

/**
 * Utility function to merge Tailwind CSS classes
 * @param inputs - Class values to merge
 * @returns Merged class string
 */
export const cn = (...inputs: ClassValue[]) => {
  return twMerge(clsx(inputs));
};

/**
 * Ensure base path ends with a slash for proper URL joining
 * @param base - The base path from import.meta.env.BASE_URL
 * @returns Base path with trailing slash
 */
export const normalizeBasePath = (base: string): string => {
  return base.endsWith('/') ? base : `${base}/`;
};
