// Generated by Copilot
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { glob } from 'glob';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface ConfigInstance {
  name: string;
  value: any;
}

interface ConfigGroup {
  schemaId: string;
  schemaPath: string;
  version: number;
  instances: ConfigInstance[];
}

interface ConfigData {
  configs: ConfigGroup[];
}

/**
 * Build config data from .configs.json files
 */
const buildConfigData = async (): Promise<void> => {
  console.log('Building config data...');

  const schemasDir = path.resolve(__dirname, '../../schemas');
  const outputDir = path.resolve(__dirname, '../public/data');

  // Ensure output directory exists
  fs.mkdirSync(outputDir, { recursive: true });

  // Find all config files
  const configFiles = glob.sync('**/*.configs.json', { cwd: schemasDir });
  console.log(`Found ${configFiles.length} config files`);

  const configs: ConfigGroup[] = [];

  // Process each config file
  for (const configFile of configFiles) {
    const fullPath = path.join(schemasDir, configFile);
    const instances = JSON.parse(fs.readFileSync(fullPath, 'utf-8'));

    // Parse version from filename: v1.configs.json -> 1
    const versionMatch = configFile.match(/v(\d+)\.configs\.json$/);
    const version = versionMatch ? parseInt(versionMatch[1]) : 1;

    // Get schema path: common/db/full/v1.configs.json -> common/db/full
    const schemaPath = path.dirname(configFile).replace(/\\/g, '/');

    // Construct schema ID
    const schemaId = `https://mapcolonies.com/${schemaPath}/v${version}`;

    configs.push({
      schemaId,
      schemaPath,
      version,
      instances,
    });
  }

  // Write output
  const configData: ConfigData = { configs };
  const outputPath = path.join(outputDir, 'configs.json');
  fs.writeFileSync(outputPath, JSON.stringify(configData, null, 2));

  console.log(`✅ Config data written to ${outputPath}`);
  console.log(`   - Total config groups: ${configs.length}`);
};

// Run the script
buildConfigData().catch((error) => {
  console.error('❌ Error building config data:', error);
  process.exit(1);
});
