// Generated by Copilot
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface GraphNode {
  id: string;
  label: string;
  path: string;
  category: string;
  version: number;
  degree: number;
}

interface GraphEdge {
  source: string;
  target: string;
  type: 'reference';
}

interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

/**
 * Build dependency graph from schema metadata
 */
const buildGraphData = async (): Promise<void> => {
  console.log('Building graph data...');

  const schemaDataPath = path.resolve(__dirname, '../public/data/schemas.json');
  const outputPath = path.resolve(__dirname, '../public/data/graph.json');

  // Read schema data
  if (!fs.existsSync(schemaDataPath)) {
    throw new Error('schemas.json not found. Run buildSchemaData.ts first.');
  }

  const schemaData = JSON.parse(fs.readFileSync(schemaDataPath, 'utf-8'));
  const schemas = schemaData.schemas;

  const nodes: GraphNode[] = [];
  const edges: GraphEdge[] = [];

  // Build nodes and edges
  for (const schema of schemas) {
    nodes.push({
      id: schema.id,
      label: schema.title,
      path: schema.path,
      category: schema.category,
      version: schema.version,
      degree: 0, // Will calculate after
    });

    // Create edges for external references
    for (const ref of schema.references) {
      edges.push({
        source: schema.id,
        target: ref,
        type: 'reference',
      });
    }
  }

  // Calculate degrees (connection count)
  for (const node of nodes) {
    const inDegree = edges.filter((e) => e.target === node.id).length;
    const outDegree = edges.filter((e) => e.source === node.id).length;
    node.degree = inDegree + outDegree;
  }

  // Write output
  const graphData: GraphData = { nodes, edges };
  fs.writeFileSync(outputPath, JSON.stringify(graphData, null, 2));

  console.log(`✅ Graph data written to ${outputPath}`);
  console.log(`   - Total nodes: ${nodes.length}`);
  console.log(`   - Total edges: ${edges.length}`);
};

// Run the script
buildGraphData().catch((error) => {
  console.error('❌ Error building graph data:', error);
  process.exit(1);
});
