// Generated by Copilot
import { useEffect, useRef, useState } from 'react';
import { EditorView } from '@codemirror/view';
import { EditorState } from '@codemirror/state';
import { json } from '@codemirror/lang-json';
import { javascript } from '@codemirror/lang-javascript';
import { oneDark } from '@codemirror/theme-one-dark';
import { Button } from './ui/button';
import { Copy, Check } from 'lucide-react';

interface CodeViewerProps {
  code: string;
  language: 'json' | 'typescript';
  readOnly?: boolean;
}

/**
 * Code viewer component with syntax highlighting using CodeMirror
 * @param code - The code to display
 * @param language - The programming language for syntax highlighting
 * @param readOnly - Whether the editor is read-only (default: true)
 */
export default function CodeViewer({ code, language, readOnly = true }: CodeViewerProps) {
  const editorRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);
  const [view, setView] = useState<EditorView | null>(null);

  useEffect(() => {
    if (!editorRef.current) return;

    const languageSupport = language === 'json' ? json() : javascript({ typescript: true });

    const state = EditorState.create({
      doc: code,
      extensions: [languageSupport, oneDark, EditorView.editable.of(!readOnly), EditorView.lineWrapping],
    });

    const editorView = new EditorView({
      state,
      parent: editorRef.current,
    });

    setView(editorView);

    return () => {
      editorView.destroy();
    };
  }, [code, language, readOnly]);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative border rounded-lg overflow-hidden">
      <Button onClick={handleCopy} className="absolute top-2 right-2 z-10" variant="secondary" size="sm">
        {copied ? <Check size={16} className="mr-1" /> : <Copy size={16} className="mr-1" />}
        {copied ? 'Copied!' : 'Copy'}
      </Button>
      <div ref={editorRef} className="codemirror-wrapper" />
    </div>
  );
}
