// Generated by Copilot
import { useState } from 'react';
import { Copy, Check } from 'lucide-react';

interface CopyableIdProps {
  id: string;
}

/**
 * Component that displays a schema ID and copies it to clipboard when clicked
 */
export default function CopyableId({ id }: CopyableIdProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(id);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="inline-flex items-center gap-2 text-sm bg-muted px-3 py-1.5 rounded border hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors cursor-pointer group"
      title="Click to copy"
    >
      <code className="text-sm">{id}</code>
      {copied ? (
        <Check className="w-3.5 h-3.5 text-green-600 dark:text-green-400" />
      ) : (
        <Copy className="w-3.5 h-3.5 text-gray-500 opacity-0 group-hover:opacity-100 transition-opacity" />
      )}
    </button>
  );
}
