// Generated by Copilot
// Using Cytoscape.js with dagre for proper left-to-right hierarchical layout
import { useEffect, useRef, useState } from 'react';
import cytoscape from 'cytoscape';
// @ts-ignore - no types available
import dagre from 'cytoscape-dagre';
import { normalizeBasePath } from '@/lib/utils';

// Register dagre layout
cytoscape.use(dagre);

interface Node {
  id: string;
  label?: string;
  title?: string;
  category: string;
  degree: number;
  path?: string;
}

interface Edge {
  source: string;
  target: string;
  type?: string;
}

interface GraphData {
  nodes: Node[];
  edges: Edge[];
}

interface ForceGraphProps {
  data: GraphData | { default: GraphData };
  focusNodeId?: string;
  onFocusChange?: (focusId: string | null) => void;
}

const COLORS = {
  common: '#3b82f6',
  infra: '#10b981',
  vector: '#f59e0b',
} as const;

export default function ForceGraph({ data, focusNodeId, onFocusChange }: ForceGraphProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const cyRef = useRef<cytoscape.Core | null>(null);
  const [focusId, setFocusId] = useState<string | null>(focusNodeId || null);

  const graphData = 'default' in data ? data.default : data;

  // Update focus when prop changes
  useEffect(() => {
    if (focusNodeId !== undefined) {
      setFocusId(focusNodeId);
    }
  }, [focusNodeId]);

  // Notify parent when focus changes
  useEffect(() => {
    onFocusChange?.(focusId);
  }, [focusId, onFocusChange]);

  useEffect(() => {
    if (!containerRef.current || !focusId) return;

    // Generated by Copilot
    // Recursively find all dependencies and dependents in same direction
    const focus = graphData.nodes.find((n) => n.id === focusId);
    if (!focus) return;

    console.log('Focus ID:', focusId);
    console.log('Focus node:', focus);

    const connected = new Set([focus.id]);

    // Recursively find all schemas this one uses (outgoing edges)
    const findUsedSchemas = (nodeId: string) => {
      graphData.edges.forEach((e) => {
        if (e.source === nodeId && !connected.has(e.target)) {
          connected.add(e.target);
          findUsedSchemas(e.target); // Recursively find dependencies
        }
      });
    };

    // Recursively find all schemas that use this one (incoming edges)
    const findUsedBySchemas = (nodeId: string) => {
      graphData.edges.forEach((e) => {
        if (e.target === nodeId && !connected.has(e.source)) {
          connected.add(e.source);
          findUsedBySchemas(e.source); // Recursively find dependents
        }
      });
    };

    findUsedSchemas(focus.id);
    findUsedBySchemas(focus.id);

    const nodes = graphData.nodes.filter((n) => connected.has(n.id));
    const edges = graphData.edges.filter((e) => connected.has(e.source) && connected.has(e.target));

    // Generated by Copilot
    // Convert to Cytoscape format with hierarchical paths as labels
    const elements = [
      ...nodes.map((n) => {
        // Extract hierarchical path from ID: https://mapcolonies.com/common/worker-boilerplate/v1 -> common/worker-boilerplate/v1
        const path = n.id.replace('https://mapcolonies.com/', '');
        const isFocused = n.id === focusId;

        // Only set isFocused property on the focused node (don't set false on others)
        const data: any = {
          id: n.id,
          label: path, // Show full hierarchical path
          fullLabel: path,
          category: n.category,
        };

        if (isFocused) {
          data.isFocused = true;
        }

        return { data };
      }),
      ...edges.map((e) => ({
        data: {
          id: `${e.source}-${e.target}`,
          source: e.source,
          target: e.target,
          label: e.type || 'ref',
        },
      })),
    ];

    // Initialize Cytoscape
    const cy = cytoscape({
      container: containerRef.current,
      elements,
      style: [
        {
          selector: 'node',
          style: {
            'background-color': (ele: any) => COLORS[ele.data('category') as keyof typeof COLORS] || '#999',
            label: 'data(label)',
            width: 60,
            height: 60,
            'font-size': 11,
            'font-weight': 500,
            'font-family': 'system-ui, -apple-system, sans-serif',
            'text-valign': 'bottom',
            'text-margin-y': 10,
            'text-wrap': 'wrap',
            'text-max-width': '180px',
            color: '#1f2937',
            'text-background-color': '#ffffff',
            'text-background-opacity': 0.95,
            'text-background-padding': '4px',
            'text-background-shape': 'roundrectangle',
            'border-width': 2,
            'border-color': '#e5e7eb',
            'border-opacity': 1,
            'background-opacity': 1,
            // Subtle shadow for depth
            'shadow-blur': 8,
            'shadow-color': '#00000015',
            'shadow-opacity': 1,
            'shadow-offset-x': 0,
            'shadow-offset-y': 2,
          } as any,
        },
        {
          selector: 'node[isFocused]',
          style: {
            // Elegant ring effect instead of thick border
            'border-width': 3,
            'border-color': '#3b82f6',
            'border-opacity': 1,
            'font-weight': 600,
            'z-index': 999,
            // Subtle glow using outline (acts like a second border)
            'outline-width': 4,
            'outline-color': '#3b82f680',
            'outline-opacity': 1,
            'outline-offset': 2,
            // Enhanced shadow for focused node
            'shadow-blur': 16,
            'shadow-color': '#3b82f630',
            'shadow-opacity': 1,
            'shadow-offset-x': 0,
            'shadow-offset-y': 4,
          } as any,
        },
        {
          selector: 'edge',
          style: {
            width: 1.5,
            'line-color': '#d1d5db',
            'target-arrow-color': '#9ca3af',
            'target-arrow-shape': 'triangle',
            'target-arrow-fill': 'filled',
            'arrow-scale': 1.2,
            'curve-style': 'bezier',
            label: 'data(label)',
            'font-size': 9,
            'font-weight': 500,
            'font-family': 'system-ui, -apple-system, sans-serif',
            'text-rotation': 'autorotate',
            'text-margin-y': -8,
            color: '#6b7280',
            'text-background-color': '#ffffff',
            'text-background-opacity': 0.95,
            'text-background-padding': '3px',
            'text-background-shape': 'roundrectangle',
          },
        },
      ],
      layout: {
        name: 'dagre',
        rankDir: 'LR',
        nodeSep: 100,
        rankSep: 150,
        padding: 50,
      } as any,
      wheelSensitivity: 0.5,
      minZoom: 0.2,
      maxZoom: 4,
    });

    cyRef.current = cy;

    // Add hover tooltips
    cy.on('mouseover', 'node', function (evt) {
      const node = evt.target;
      const nodeData = graphData.nodes.find((n) => n.id === node.id());

      if (nodeData) {
        const tooltip = document.createElement('div');
        tooltip.id = 'cy-tooltip';
        tooltip.style.cssText = `
          position: fixed;
          background: #000;
          color: #fff;
          padding: 8px 12px;
          border-radius: 6px;
          font-size: 11px;
          pointer-events: none;
          z-index: 9999;
          max-width: 400px;
          word-break: break-all;
        `;
        tooltip.innerHTML = `<strong>${nodeData.label || nodeData.title}</strong><br/><small>${nodeData.id}</small>`;
        document.body.appendChild(tooltip);
      }
    });

    cy.on('mousemove', 'node', function (evt) {
      const tooltip = document.getElementById('cy-tooltip');
      if (tooltip) {
        tooltip.style.left = evt.originalEvent.pageX + 10 + 'px';
        tooltip.style.top = evt.originalEvent.pageY - 10 + 'px';
      }
    });

    cy.on('mouseout', 'node', function () {
      const tooltip = document.getElementById('cy-tooltip');
      if (tooltip) tooltip.remove();
    });

    // Click handler - navigate directly to schema page
    cy.on('tap', 'node', function (evt) {
      const node = evt.target;
      const nodeData = graphData.nodes.find((n) => n.id === node.id());
      if (nodeData) {
        const base = normalizeBasePath(import.meta.env.BASE_URL || '/');
        const path = nodeData.id.replace('https://mapcolonies.com/', '');
        window.location.href = `${base}schema/${path}`;
      }
    });

    // Add hover cursor style
    cy.on('mouseover', 'node', function (evt) {
      document.body.style.cursor = 'pointer';
    });

    cy.on('mouseout', 'node', function () {
      document.body.style.cursor = 'default';
    });

    return () => {
      cy.destroy();
    };
  }, [graphData, focusId]);

  return (
    <div className="relative w-full h-full">
      <div ref={containerRef} className="w-full h-full" />

      <div className="absolute top-4 right-4 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg p-4 text-xs shadow-lg max-w-[220px]">
        <div className="font-semibold text-sm mb-3 text-gray-900 dark:text-gray-100">Legend</div>

        <div className="mb-4">
          <div className="font-medium text-gray-700 dark:text-gray-300 mb-2 text-[11px]">Categories</div>
          {Object.entries(COLORS).map(([cat, color]) => {
            const count = graphData.nodes.filter((n: Node) => n.category === cat).length;
            return (
              <div key={cat} className="flex items-center gap-2 mb-2">
                <div className="w-4 h-4 rounded-full flex-shrink-0 border border-gray-200" style={{ backgroundColor: color }} />
                <span className="capitalize text-gray-700 dark:text-gray-300">{cat}</span>
                <span className="text-gray-500 dark:text-gray-400 ml-auto">({count})</span>
              </div>
            );
          })}
        </div>

        <div className="mb-4 pb-3 border-t border-gray-200 dark:border-gray-700 pt-3">
          <div className="flex items-center gap-2">
            <div className="relative w-4 h-4 flex-shrink-0">
              <div className="absolute inset-0 rounded-full border-2 border-blue-500" style={{ backgroundColor: '#3b82f6' }} />
              <div className="absolute inset-[-2px] rounded-full border-2 border-blue-500/50" />
            </div>
            <span className="font-medium text-gray-900 dark:text-gray-100">Current schema</span>
          </div>
        </div>

        <div className="pt-3 border-t border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400">
          <div className="font-medium mb-2 text-[11px]">Controls</div>
          <div className="space-y-1">
            <div>• Hover for details</div>
            <div>• Click to navigate</div>
            <div>• Scroll to zoom</div>
            <div>• Drag to pan</div>
          </div>
        </div>
      </div>
    </div>
  );
}
