// Generated by Copilot
import { useState } from 'react';
import SearchBar from './SearchBar';
import ForceGraph from './ForceGraph';

interface GraphData {
  nodes: Array<{
    id: string;
    label?: string;
    title?: string;
    category: string;
    degree: number;
    path?: string;
  }>;
  edges: Array<{
    source: string;
    target: string;
    type?: string;
  }>;
}

interface GraphWithSearchProps {
  data: GraphData | { default: GraphData };
}

/**
 * Wrapper component that connects SearchBar with ForceGraph
 * Handles focus state between search and graph visualization
 */
export default function GraphWithSearch({ data }: GraphWithSearchProps) {
  const [focusNodeId, setFocusNodeId] = useState<string | undefined>(undefined);

  const handleSchemaSelect = (schemaId: string) => {
    setFocusNodeId(schemaId);
  };

  const handleFocusChange = (focusId: string | null) => {
    setFocusNodeId(focusId || undefined);
  };

  return (
    <div className="relative w-full h-full">
      {/* Search overlay positioned at top */}
      <div className="absolute top-4 left-4 z-10">
        <SearchBar onSchemaSelect={handleSchemaSelect} />
      </div>

      {/* Graph visualization */}
      <ForceGraph data={data} focusNodeId={focusNodeId} onFocusChange={handleFocusChange} />
    </div>
  );
}
