// Generated by Copilot
import { useState, useEffect } from 'react';
import { Moon, Sun } from 'lucide-react';
import { Button } from './ui/button';

/**
 * Theme toggle component for switching between light and dark mode
 */
export default function ThemeToggle() {
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    // Check localStorage on mount
    const isDark = localStorage.getItem('darkMode') === 'true';
    setDarkMode(isDark);
  }, []);

  const toggleDarkMode = () => {
    const newMode = !darkMode;
    setDarkMode(newMode);
    localStorage.setItem('darkMode', newMode.toString());
    document.documentElement.classList.toggle('dark', newMode);
  };

  return (
    <Button onClick={toggleDarkMode} variant="ghost" size="icon" aria-label="Toggle theme">
      {darkMode ? <Sun size={20} /> : <Moon size={20} />}
    </Button>
  );
}
