name: pull_request

on: [pull_request, workflow_dispatch]

permissions:
  pull-requests: write
  contents: read

jobs:
  validate_schemas:
    name: validate schemas
    runs-on: ubuntu-latest

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v4

      - name: Init nodejs
        uses: ./.github/actions/init-npm

      - name: Run the validations
        run: npm run validate

  check_for_changed_files:
    name: check for changed schemas
    runs-on: ubuntu-latest

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: '0'

      - name: Init nodejs
        uses: ./.github/actions/init-npm

      - name: Run the validations
        run: npm run check-files-changed

  upload_package:
    needs: [validate_schemas, check_for_changed_files]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v4
      - name: Init nodejs
        uses: ./.github/actions/init-npm

      - name: Pack the package
        run: npm pack
      - name: get properties
        id: json_properties
        uses: ActionsTools/read-json-action@main
        with:
          file_path: 'package.json'
      - uses: azure/CLI@v2
        env:
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.SAS_TOKEN }}
        with:
          inlineScript: |
            az storage blob upload --name schemas-$GITHUB_SHA.tgz --account-name ghatmpstorage --container-name=npm-packages --file map-colonies-schemas-${{steps.json_properties.outputs.version}}.tgz
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hi it is me, your friendly bot helper! :wave:
            I've packed this commit for you :blush:
            You can install it like this:
            ```json
            {
              "dependencies": {
                  "@map-colonies/schemas": "https://ghatmpstorage.blob.core.windows.net/npm-packages/schemas-${{ github.sha }}.tgz"
              }
            }
            ```
            The link will expire in a week :hourglass:
